### ISSUE TITLE
Exception becuase of missing math package

### ISSUE THREAD

**Issue by hcarter333** [hcarter333/datasette-haversine-point-path#4]
Getting the following from pytest:

```
Traceback (most recent call last):
  File "/home/hcarter333/datasette-haversine-point-path/datasette_haversine_point_path/__init__.py", line 36, in haversine_point_path_sql
    tx_x = cartesian_x(lat1,lon1)
  File "/home/hcarter333/datasette-haversine-point-path/datasette_haversine_point_path/__init__.py", line 7, in cartesian_x
    return (math.cos(f*deg2rad)*math.cos(l*deg2rad))
NameError: name 'math' is not defined
```

I'll add the path and I'll also add the dependeny to pyproject.toml.

**Comment by hcarter333** [comment]
math package now found. The new issue is that my 'constant' deg2rad is missing.

**Comment by hcarter333** [comment]
That fixed this issue.
