### ISSUE TITLE
Inputs need type conversion

### ISSUE THREAD

**Issue by hcarter333** [hcarter333/datasette-haversine-point-path#5]
In case the database hands in floats coded as strings, they need to be cast back to floats. This same [issue](https://github.com/simonw/datasette-haversine/issues/1) occurred in datasette-haversine which is where the test case for this package originated. Here's the error message

```
Traceback (most recent call last):
  File "/home/hcarter333/datasette-haversine-point-path/datasette_haversine_point_path/__init__.py", line 39, in haversine_point_path_sql
    tx_x = cartesian_x(lat1,lon1)
  File "/home/hcarter333/datasette-haversine-point-path/datasette_haversine_point_path/__init__.py", line 10, in cartesian_x
    return (math.cos(f*deg2rad)*math.cos(l*deg2rad))
TypeError: can't multiply sequence by non-int of type 'float'

```
the fix will be to convert the inputs into floats.

**Comment by hcarter333** [comment]
Last commit fixed the issue.
